spring.application.name=todos

# ===============================
# H2 DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# ===============================
# JPA / HIBERNATE
# ===============================


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true

# ===============================
# H2 CONSOLE
# ===============================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.security.user.name=sha
spring.security.user.password=password


spring.jwt.secret=f02176f1a24b220405903825ced10024892fb180ee8dd1c10d59cb89d2f50836
spring.jwt.expiration=900000