/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Product product = new Product();
        System.out.println("Product name :"+product.name);
        System.out.println("Product Description :"+product.description);
        System.out.println("Product price :"+product.price);
    }
}
